### ISSUE TITLE
Compiler warnings for var 'coderef' during build on Debian Buster with gcc

### ISSUE THREAD

**Issue by tbrowder** [MoarVM/MoarVM#1469]

**Comment by coke** [comment]
Can you include the details of the warning? files, line numbers, etc?

**Comment by tbrowder** [comment]
Sure, will do...

**Comment by tbrowder** [comment]
Partial config/compile log showing pertinent details:

```
Fetching submodule 3rdparty/nqp-configure
HEAD is now at f1469fad3 [release] Bump VERSION to 2021.04
Building NQP ...
/usr/bin/perl Configure.pl --prefix=/home/tbrowde/rakudo/.- --make-install --git-protocol=https --no-relocatable --no-ignore-errors --silent-build --no-force-rebuild --backends=moar --gen-moar
HEAD is now at 239d0b7c9 Bump VERSION for release

Configuring and building MoarVM ...

    probing whether your compiler thinks that it is gcc  YES

        make: make
     compile: gcc -std=gnu99 -Wextra -Wall -Wno-unused-parameter -Wno-unused-function -Wno-missing-braces -Werror=pointer-arith -O3 -DNDEBUG  -D_REENTRANT -D_FILE_OFFSET_BITS=64 -fPIC -DMVM_HEAPSNAPSHOT_FORMAT=3
    includes:   -I3rdparty/libuv/include -I3rdparty/libuv/src -I3rdparty/libatomicops/src -I3rdparty/libtommath -I3rdparty/dyncall/dynload -I3rdparty/dyncall/dyncall -I3rdparty/dyncall/dyncallback
        link: gcc  -O3 -DNDEBUG -Wl,-rpath,"/@libdir@"
        libs:  -lm -lpthread -lrt -ldl -lzstd

Configuration SUCCESS.

Type 'make' to build and 'make help' to see a list of
available make targets.
#  [make]...
compiling src/core/interp.o
src/core/interp.c: In function 'MVM_interp_run':
src/core/interp.c:3311:36: warning: variable 'coderef' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
                         MVMObject *coderef;
                                    ^~~~~~~
compiling src/strings/windows1252.o
compiling src/strings/shiftjis.o
In file included from src/moar.h:191,
                 from src/strings/shiftjis.c:1:
src/strings/shiftjis.c: In function 'MVM_string_shiftjis_decodestream':
src/strings/decode_stream.h:99:16: warning: 'codepoint' may be used uninitialized in this function [-Wmaybe-uninitialized]
             if (sep_spec->final_graphemes[i] == g)
                ^
src/strings/shiftjis.c:353:26: note: 'codepoint' was declared here
             MVMCodepoint codepoint;
                          ^~~~~~~~~
...
Using /home/tbrowde/rakudo/.-/bin/nqp-m (version 2021.04 / MoarVM 2021.04).
Cleaning up ...
```

**Comment by tbrowder** [comment]
When compiling MaoarVM alone I get some additional warnings from 3rd party libraries:

```
compiling 3rdparty/libuv/src/unix/core.o
3rdparty/libuv/src/unix/core.c: In function 'uv__accept':
3rdparty/libuv/src/unix/core.c:88:22: warning: implicit declaration of function 'accept4'; did you mean 'accept'? [-Wimplicit-function-declaration]
 # define uv__accept4 accept4
                      ^~~~~~~
3rdparty/libuv/src/unix/core.c:498:14: note: in expansion of macro 'uv__accept4'
     peerfd = uv__accept4(sockfd, NULL, NULL, SOCK_NONBLOCK|SOCK_CLOEXEC);
              ^~~~~~~~~~~
3rdparty/libuv/src/unix/core.c: In function 'uv__dup2_cloexec':
3rdparty/libuv/src/unix/core.c:1034:7: warning: implicit declaration of function 'dup3'; did you mean 'dup2'? [-Wimplicit-function-declaration]
   r = dup3(oldfd, newfd, O_CLOEXEC);
       ^~~~
       dup2

compiling 3rdparty/libuv/src/unix/pipe.o
3rdparty/libuv/src/unix/pipe.c: In function 'uv_pipe':
3rdparty/libuv/src/unix/pipe.c:393:7: warning: implicit declaration of function 'pipe2'; did you mean 'pipe'? [-Wimplicit-function-declaration]
   if (pipe2(temp, flags))
       ^~~~~
       pipe
```

**Comment by tbrowder** [comment]
I just filed libuv warnings as issue #??? at the libuv site.

**Comment by tbrowder** [comment]
The latest from the libuv folks, ref their issue #3164:

**Comment by MasterDuke17** [comment]
I looked at the Makefile I have currently in MoarVM and if I'me reading it correctly, we don't use the build scripts, and instead just list the particular libuv source files we need (e.g., https://github.com/MoarVM/MoarVM/blob/master/build/Makefile.in#L452-L481) to be compiled individually. I guess we could add `-D_GNU_SOURCE` to our overall flags. However, dyncall does also use `_GNU_SOURCE`, so we'd have to make sure that doesn't cause a problem. Also, we do conditionally define `_GNU_SOURCE` in a couple of our source files (https://github.com/MoarVM/MoarVM/blob/master/src/moar.h#L4-L9, https://github.com/MoarVM/MoarVM/blob/master/src/platform/memmem.h#L13-L15, and https://github.com/MoarVM/MoarVM/blob/master/src/platform/random.c#L13-L26) so those need to be reviewed.

**Comment by tbrowder** [comment]
Maybe split out libuv as a separate compile source group (as it is already), but keep it separate through the compile step with its own flags.  Some Make guru should be able to do that.

**Comment by tbrowder** [comment]
See PRs #1497 and #1497 which fix all the warnings for me **without requiring any 3rdparty source code changes**.
