### ISSUE TITLE
Runtime error on OS X 10.11 (El Cap) with Xcode 8.0

### ISSUE THREAD

**Issue by donaldh** [MoarVM/MoarVM#437]
After upgrading to Xcode 8.0 MoarVM still builds but fails at runtime with the following error:

dyld: Symbol not found: _clock_gettime
Referenced from: /usr/local/Cellar/rakudo-star/2016.10/lib/libmoar.dylib
Expected in: /usr/lib/libSystem.B.dylib

This seems to be caused by clock_gettime being defined in the headers but not actually available in the dylib. This problem has cropped up across many open source projects in homebrew, with different workarounds depending on whether they use autoconf or not.

As far as I can see, MoarVM does not probe for clock_gettime but has conditional code that checks for CLOCK_REALTIME.

The homebrew workaround I am using is to force the fallback by patching time.c:
inreplace %w[MoarVM/src/platform/posix/time.c], "CLOCK_REALTIME", "UNDEFINED_XCODE8_HACK"

I don't know what the success/failure mode is on 10.12 (Sierra) with Xcode 8.0 because I have yet to upgrade.

**Comment by FROGGS** [comment]
Please test the branch `mach-clock_gettime` I just created.

**Comment by donaldh** [comment]
Looks good, FROGGS++
Builds on OSX 10.11.6, Xcode 8.0, CmdLineTools 7.3.1.0.1 and all Rakudo tests pass.

**Comment by donaldh** [comment]
Will be able to test on OSX 10.12, Xcode 8.1 but travelling so might be a day or so before I manage to.

**Comment by FROGGS** [comment]
Awesome! If it also works on 10.12, I'll merge the PR.

Thanks for testing!

**Comment by FROGGS** [comment]
Hi, were you able to test on 10.12?

**Comment by donaldh** [comment]
Hi,

My apologies, I did test this but while travelling forgot to reply.

Your MoarVM branch builds on macOS 10.12.1, Xcode 8.1, CLT 8.1.0.0.1 and
all Rakudo spectests pass.

**Comment by FROGGS** [comment]
Thanks for testing :o)
