### ISSUE TITLE
Unable to build in a RHEL 7.9

### ISSUE THREAD

**Issue by demanuel** [MoarVM/MoarVM#1700]
Hi.

My **work** machine is a RHEL 7.9, and i'm trying to install rakudo with rakubrew. Unfortunately it's failing with the error:

```
src/jit/x64/emit.dasc:6:9: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wimplicit-fallthrough"
         ^
compiling src/jit/x64/arch.o
linking libmoar.so
linking moar
./libmoar.so: undefined reference to `uv__cloexec_ioctl'
collect2: error: ld returned 1 exit status
make: *** [moar] Error 1
Command failed (status 512): /home/demanuel/perl5/perlbrew/perls/perl-5.20.3/bin/perl Configure.pl --optimize --git-cache-dir=/home/demanuel/.rakubrew/git_reference --prefix=/home/demanuel/.rakubrew/versions/moar-master/install --make-install
 at /home/demanuel/.rakubrew/versions/moar-master/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 34.
        NQP::Config::__ANON__("Command failed (status 512): /home/demanuel/perl5/perlbrew/perls"...) called at /home/demanuel/.rakubrew/versions/moar-master/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 1502
        NQP::Config::system_or_die("/home/demanuel/perl5/perlbrew/perls/perl-5.20.3/bin/perl", "Configure.pl", "--optimize", "--git-cache-dir=/home/demanuel/.rakubrew/git_reference", "--prefix=/home/demanuel/.rakubrew/versions/moar-master/install", "--make-install") called at /home/demanuel/.rakubrew/versions/moar-master/nqp/tools/lib/NQP/Config/NQP.pm line 426
        NQP::Config::NQP::gen_moar(NQP::Config::NQP=HASH(0x1036f28)) called at /home/demanuel/.rakubrew/versions/moar-master/nqp/tools/lib/NQP/Config/NQP.pm line 105
        NQP::Config::NQP::configure_moar_backend(NQP::Config::NQP=HASH(0x1036f28)) called at /home/demanuel/.rakubrew/versions/moar-master/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 666
        NQP::Config::configure_active_backends(NQP::Config::NQP=HASH(0x1036f28)) called at Configure.pl line 93
Command failed (status 512): /home/demanuel/perl5/perlbrew/perls/perl-5.20.3/bin/perl Configure.pl --prefix=/home/demanuel/.rakubrew/versions/moar-master/install --make-install --git-protocol=https --no-relocatable --no-ignore-errors --silent-build --no-force-rebuild --git-cache-dir=/home/demanuel/.rakubrew/git_reference --backends=moar --gen-moar
 at /home/demanuel/.rakubrew/versions/moar-master/3rdparty/nqp-configure/lib/NQP/Config.pm line 34.
        NQP::Config::__ANON__("Command failed (status 512): /home/demanuel/perl5/perlbrew/perls"...) called at /home/demanuel/.rakubrew/versions/moar-master/3rdparty/nqp-configure/lib/NQP/Config.pm line 1502
        NQP::Config::system_or_die("/home/demanuel/perl5/perlbrew/perls/perl-5.20.3/bin/perl", "Configure.pl", "--prefix=/home/demanuel/.rakubrew/versions/moar-master/install", "--make-install", "--git-protocol=https", "--no-relocatable", "--no-ignore-errors", "--silent-build", "--no-force-rebuild", ...) called at /home/demanuel/.rakubrew/versions/moar-master/tools/lib/NQP/Config/Rakudo.pm line 724
        NQP::Config::Rakudo::gen_nqp(NQP::Config::Rakudo=HASH(0x1ce9f28)) called at Configure.pl line 101
Failed running /home/demanuel/perl5/perlbrew/perls/perl-5.20.3/bin/perl Configure.pl --backends=moar --gen-moar --make-install  --git-cache-dir="/home/demanuel/.rakubrew/git_reference" at /home/demanuel/Applications/rakubrew/bin/rakubrew line 752.
```

[full output](https://github.com/MoarVM/MoarVM/files/8462919/rakubrew_output.txt)

I know that this is a distro with ancient packages, but would it be possible to build it?

**Comment by MasterDuke17** [comment]
I ran into the same problem `./libmoar.so: undefined reference to 'uv__cloexec_ioctl'
collect2: error: ld returned 1 exit status` when rebuilding MoarVM after the most recent libuv bump. I think it was a `make realclean` that fixed it for me. I'm not sure how rakubrew works, but if it's using a shared MoarVM to build then you might need to manually run that in its MoarVM checkout (I'm guessing somewhere in `/home/demanuel/.rakubrew/`).

**Comment by demanuel** [comment]
@MasterDuke17 

Thanks for the tip. I did `make realclean` inside of `/home/demanuel/.rakubrew/versions/moar-master` and it didn't help. So i deleted the folder `moar-master` so that rakubrew would check it out again and then it worked!

Thanks for the help :-)
