### ISSUE TITLE
symbol collision between MoarVM and libtommath v1.1.0-rc1

### ISSUE THREAD

**Issue by dod38fr** [MoarVM/MoarVM#1032]
Hello

moarvm fails to compile with the next libtommath release (1.1.0-rc1):
```
gcc -c -Werror=declaration-after-statement -Werror=pointer-arith -O3 -DNDEBUG -g3  -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DHAVE_LIBFFI -fPIC -DDEBUG_HELPERS -g -O2 -fdebug-prefix-map=/home/domi/debian-dev/build-area/moarvm-2018.12+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DMVM_TRACING=0 -DMVM_CGOTO=1 -DMVM_RDTSCP=1 -DMVM_BUILD_SHARED -fPIC -I/usr/local/include -I3rdparty/sha1 -I3rdparty/tinymt -I3rdparty/dynasm -I3rdparty/cmp -I3rdparty -Isrc -o src/math/bigintops.o src/math/bigintops.c
src/math/bigintops.c:64:17: error: conflicting types for ‘mp_get_double’
 static MVMnum64 mp_get_double(mp_int *a, int shift) {
                 ^~~~~~~~~~~~~
In file included from src/6model/reprs/P6bigint.h:1,
                 from src/6model/reprs.h:21,
                 from src/moar.h:128,
                 from src/math/bigintops.c:1:
/usr/include/tommath.h:217:8: note: previous declaration of ‘mp_get_double’ was here
 double mp_get_double(const mp_int *a);
        ^~~~~~~~~~~~~
```

I'll let you check with libtommath team how to resolve this issue.

All the best

**Comment by czurnieden** [comment]
Hi,

The function `mp_get_double` is new in libtommath and functionally equivalent with your implementation sans the `shift` argument. I think it would be least amount of hassle for both of us if you change the name.
It is a `static` function and hence would be much easier for you to keep your code and just change the name to something like e.g.: `s_mp_get_double` than it would be for us to change the API.

We would be *very*  thankful!

**Comment by minad** [comment]
What does this shift argument do? Maybe this could be upstreamed as mp_get_double_shift. 

Moar also implements its own two complement bitops which are now provided by tommath.
