### ISSUE TITLE
src/core/interp.c:4836: error: ‘MVMIterBody’ has no member named ‘array_state’

### ISSUE THREAD

**Issue by ronaldxs** [MoarVM/MoarVM#211]
I am running an old system but the fix seems easy enough that it looks worth doing.  My build of MoarVM is breaking with the error in the subject because of a clash between the use of an anonymous union in src/6model/reprs/MVMIter.h and the new -std=c99 flag introduced with pull request #202 a few days ago.

src/core/interp.c:4836: error: ‘MVMIterBody’ has no member named ‘array_state’

It looks like the easiest solution is to add the -fms-extensions flag to gcc in build/setup.pm near where the -std=c99 was added.  The flag is documented here: https://gcc.gnu.org/onlinedocs/gcc/Unnamed-Fields.html

Alternatively one might decide to give the anonymous 'C' union a name which seems to match most other unions in the code and may be more standard - I am not 100% sure.

I am running Ubunto 10.04 and gcc 4.4.3 which may be out of date but again it looks plausibly reasonable to fix.
